### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by whazor** [Whazor/redux-observable-thunk#2]
I welcome feedback whether everything is smooth with all the libraries and new methods.

**Comment by anodynos** [comment]
Hey @whazor this looks like what I was looking for, thanks! 
Just one initial question, has it being used in the battlefield, is it stable to adopt?

**Comment by whazor** [comment]
All APIs so far work fine, let me know if you would like to see any improvements or if you are having type problems. Production-wise it does not really add that much JavaScript (in total the JS is 53 lines), and it mostly wraps other functions from `rxjs/operators` and `@reduxjs/toolkit`.

I just released 2.0.2, which bumps all the dev versions and fixes one type issue.
